### ISSUE TITLE
NTWE special issue

### ISSUE THREAD

**Issue by thin-lizard** [BITS-Research/DRC#13]

**Comment by thin-lizard** [comment]
[NTWE special issue](https://onlinelibrary.wiley.com/pb-assets/assets/1468005X/NTWE_SI_CFP_WORK,%20EMPLOYMENT%20AND%20RESISTANCE%20IN%20TRANSPORTATION%20PLATFORMS-1659099646003.pdf) - send abstract in advance; submission deadline January 2023

**Comment by nniiicc** [comment]
Deadline: 31 st January 2023.

**Comment by thin-lizard** [comment]
Abstract swap 11/30

**Comment by thin-lizard** [comment]
Abstract draft - https://docs.google.com/document/d/1TVflTynO6cov1RrGBmsxXVM1W0QX-88mTbv6HDw88Ig/edit

**Comment by thin-lizard** [comment]
send out 1 pager by 12-08

**Comment by thin-lizard** [comment]
@nniiicc - [here](https://docs.google.com/document/d/1TVflTynO6cov1RrGBmsxXVM1W0QX-88mTbv6HDw88Ig/edit#bookmark=id.jk7p5i26wnxd) is my writeup on our theoretical contribution. I'm slightly concerned that "platform exceptionalism" is not the strongest theory - I will keep looking this over, and would appreciate if you could read through it. The main piece of feedback I'd like is whether our case study and van doorn's theory fit together. thank you!
