### ISSUE TITLE
Focus group analysis

### ISSUE THREAD

**Issue by thin-lizard** [BITS-Research/DRC#21]
https://docs.google.com/document/d/1nW1iOaliy1RZLnEy_m0mh5M2GIaHz1zzRTYsAG13Pag/edit

**Comment by thin-lizard** [comment]
https://docs.google.com/spreadsheets/d/19t9o7g8g9L-XNuegdfTA4UBpOZCb8DuwVJQOQhxqc6I/edit#gid=0

**Comment by nniiicc** [comment]
@nniiicc Please give feedback needed for content and for structure...

**Comment by nniiicc** [comment]
Advice on connecting to relevant work ...
