### ISSUE TITLE
DRC Questionnaire

### ISSUE THREAD

**Issue by nniiicc** [BITS-Research/DRC#3]
As a starting point https://docs.google.com/document/d/1Uh0OrzeMbgcKM4Drkkt_DnDJDguoj12p3bE_lRhPh6w/edit

**Comment by thin-lizard** [comment]
See recent draft [here](https://docs.google.com/document/d/1Rim14EfBUStG-Pi-NwZtJq8VUvyHgJyfk8WLZr64fHc/edit). Comments are directed towards DRC reps. I drafted it based on the GigPlat interviews-- along with the DRC group's feedback, this will pry need revision based on: 

1. format [phone survey and / or interviews conducted by us]
2. scoping and time [how long the survey or interview will take]

When we present this, I'll ask about following up with Joshua, who sounded like the point person for the UW Public Health study. I met him in the first meeting, which is a +

**Comment by thin-lizard** [comment]
Working drafts for the driver survey and focus groups are in the wiki under [Survey & focus group materials](https://github.com/BITS-Research/DRC/wiki/Survey-&-focus-group-materials). The survey questions include additional Qs shared by Vince after our meeting on 05.19
